language: ruby

rvm:
  - 2.2

before_script:
  - gem install awesome_bot
  - gem install mdl

script:
- awesome_bot README.md --allow-dupe -w jinja.pocoo.org # Allow duplicate links and whitelist jinja.pocoo.org
- mdl --rules ~MD013,~MD033 README.md # Ignore line length (MD013) and inline HTML (MD033) Rules
